-record(yahoo_notification, {sequence = 0, responses = []}).
-record(yahoo_buddy_info, {contact_ids = []}).
-record(yahoo_buddy_status, {}).
-record(yahoo_log_off, {contact_id}).
-record(yahoo_message, {contact_id, timestamp, text}).
-record(yahoo_offline_message, {messages}).
-record(yahoo_disconnect, {reason}).
